apiVersion: v1
kind: ConfigMap
metadata:
  name: customer-saved-job
  namespace: projectsveltos
  annotations:
    projectsveltos.io/instantiate: ok
data:
  job.yaml: |
    {{ range $index, $user := .CloudEvent.data.users }}
    ---
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: save-user-data-{{ $index }}-{{ $.CloudEvent.subject }}
      namespace: default
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: knapscen-save-user-data
            image: ghcr.io/colinjlacy/knapscen-register-users:latest
            envFrom:
            - secretRef:
                name: knapscen-config
            env:
            - name: CUSTOMER_NAME
              value: "{{ $.CloudEvent.data.name }}"
            - name: USER_NAME
              value: "{{ $user.name }}"
            - name: USER_EMAIL
              value: "{{ $user.email }}"
            - name: USER_ROLE
              value: "{{ $user.role }}"
    {{ end }}