apiVersion: v1
kind: Secret
metadata:
  name: knapscen-config
  namespace: default
type: Opaque
stringData:
  # Database Configuration
  DB_HOST: "my-test-cluster.default.svc.cluster.local"
  DB_PORT: "3306"
  DB_USER: "bassline-boogie-user"
  DB_PASSWORD: "8Qd8*yZK&zIxS%!s"
  DB_NAME: "bassline-boogie"
  
  # NATS JetStream Configuration
  NATS_SERVER: "nats://nats.nats.svc.cluster.local:4222"
  NATS_STREAM: "customer-onboarding"
  NATS_SUBJECT: "customer-saved"
  NATS_USER: "admin"
  NATS_PASSWORD: "admin"

  # SMTP Configuration
  SMTP_HOST: "mailhog.default.svc.cluster.local"
  SMTP_PORT: "1025"
  SMTP_USER: "admin"
  SMTP_PASSWORD: "admin"
